# Workflowの名前
name: java mvn test

# Workflowを動かすトリガー（=Event）を指定。
# 今回はpushをEventに設定
on:
  - push

jobs:
  # build job
  build:
    # Runnerを指定
    runs-on: ubuntu-latest
    # Step
    steps:
      # RunnnerにGitリポジトリのコピーをダウンロード
      - uses: actions/checkout@v3
      # Java 17をセットアップ
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      # maven build
      - name: Build with Maven
        run: mvn clean package
        working-directory: ./java_test3
      # Test実行
      - name: Test with Maven
        run: mvn verify
        working-directory: ./kanri
