name: Java Maven Test with MySQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    services:
      kanri_mysql:
        image: mysql:8.0
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: rootroot
          MYSQL_DATABASE: kanrichan
          MYSQL_USER: shunuser
          MYSQL_PASSWORD: mysql0710
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -ushunuser -pmysql0710 -e'select user();'"
#          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -prootroot"
          --health-interval=10s
          --health-retries=15
        volumes:
          - ./docker/mysql/compose-volumes/docker-entrypoint-initdb.d/01_kanri.sql:/docker-entrypoint-initdb.d/01_kanri.sql
          - ./docker/mysql/compose-volumes/docker-entrypoint-initdb.d/02_kanri_data.sql:/docker-entrypoint-initdb.d/02_kanri_data.sql
          - ./docker/mysql/compose-volumes/docker-entrypoint-initdb.d/03_create_user.sql:/docker-entrypoint-initdb.d/03_create_user.sql
          - ./docker/mysql/compose-volumes/etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if mysql -h 127.0.0.1 -ushunuser -pmysql0710 -e 'SELECT 1'; then
              echo "MySQL is ready!"
              break
            fi
            echo "MySQL is not ready yet. Retrying in 5 seconds..."
            sleep 5
          done

      - name: Run Maven Verify
        run: mvn verify
