name: Java Maven Test with MySQL

on:
  push:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: Javaのセットアップ
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # OpenJDK（Eclipse Temurin）を使用
          java-version: '11'       # 必要なJavaのバージョンを指定
          cache: 'maven'           # Mavenの依存関係をキャッシュ

      - name: Maven Verifyの実行
        run: mvn verify